#!/bin/sh
#
# simple memory status for linux and OpenBSD
#

case $(uname) in
    OpenBSD)
        used=`vmstat | grep M | awk '{print $4}' | grep -oE '([0-9]*)'`
        total=`dmesg | grep 'real mem' | awk '{print $5}' | tr -d '()' | grep -oE '([0-9]*)'`
        ;;
    Linux)
        used=`free --mega | grep Mem | awk '{print $3}' | grep -oE '([0-9]*)'`
        total=`free --mega | grep Mem | awk '{print $2}' | grep -oE '([0-9]*)'`
        ;;
esac

format_mem() {
    echo "scale=2; $1 / 1024" | bc
}

echo "$( format_mem $used )/$( format_mem $total )"GB
