#!/bin/dash
#
# simple memory status for linux and OpenBSD
#

case $(uname) in
    OpenBSD)
        used=`vmstat | grep M | awk '{print $3}' | grep -oE '([0-9]*)'`
        total=`dmesg | grep 'real mem' | awk '{print $5}' | tr -d '()' | grep -oE '([0-9]*)'`
        total="$(($(sysctl -n hw.physmem) / 1024 / 1024))"
	;;
    Linux)
        used=`free --mega | grep Mem | awk '{print $3}' | grep -oE '([0-9]*)'`
        total=`free --mega | grep Mem | awk '{print $2}' | grep -oE '([0-9]*)'`
        ;;
esac

format_mem() {
    if [ $1 -lt 1024 ]; then 
        num=0;
    fi
    echo "$num$(echo "scale=2; $1 / 1024" | bc)"
}


case $1 in
    -g)
        echo "Memory Usage: $(format_mem $used)GiB / $( format_mem $total )GiB"
        ;;
    -m)
        echo Memory Usage: "$used"MiB / "$total"MiB
	;;
    *)
        echo "Usage: \n    -m | megabytes \n    -g | gigabytes"
esac
